<?php

namespace ContainerIQl6aKb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_38L_QV1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.38L.QV1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.38L.QV1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\AvisController::delete' => ['privates', '.service_locator.WAdf4Q1', 'get_ServiceLocator_WAdf4Q1Service', true],
            'App\\Controller\\AvisController::edit' => ['privates', '.service_locator.WAdf4Q1', 'get_ServiceLocator_WAdf4Q1Service', true],
            'App\\Controller\\AvisController::index' => ['privates', '.service_locator.T61jM.4', 'get_ServiceLocator_T61jM_4Service', true],
            'App\\Controller\\AvisController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvisController::show' => ['privates', '.service_locator.tqKaOKq', 'get_ServiceLocator_TqKaOKqService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\AvisController:delete' => ['privates', '.service_locator.WAdf4Q1', 'get_ServiceLocator_WAdf4Q1Service', true],
            'App\\Controller\\AvisController:edit' => ['privates', '.service_locator.WAdf4Q1', 'get_ServiceLocator_WAdf4Q1Service', true],
            'App\\Controller\\AvisController:index' => ['privates', '.service_locator.T61jM.4', 'get_ServiceLocator_T61jM_4Service', true],
            'App\\Controller\\AvisController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\AvisController:show' => ['privates', '.service_locator.tqKaOKq', 'get_ServiceLocator_TqKaOKqService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\AvisController::delete' => '?',
            'App\\Controller\\AvisController::edit' => '?',
            'App\\Controller\\AvisController::index' => '?',
            'App\\Controller\\AvisController::new' => '?',
            'App\\Controller\\AvisController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AvisController:delete' => '?',
            'App\\Controller\\AvisController:edit' => '?',
            'App\\Controller\\AvisController:index' => '?',
            'App\\Controller\\AvisController:new' => '?',
            'App\\Controller\\AvisController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
