# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: _username
                password_parameter: _password
               # default_target_path: app_home
                failure_path: app_login
                failure_forward: false
            logout:
                path: app_logout
                target: app_login


    role_hierarchy:
        ROLE_ADMIN: [ ROLE_DRIVER, ROLE_TAXI, ROLE_CLIENT, ROLE_USER ]
        ROLE_DRIVER: ROLE_TAXI
        ROLE_TAXI: ROLE_CLIENT
        ROLE_CLIENT: ROLE_USER

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin/users/edit, roles: ROLE_ADMIN }
        - { path: ^/admin/users/block, roles: ROLE_ADMIN }
        - { path: ^/admin/users/unblock, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/driver, roles: ROLE_DRIVER }
        - { path: ^/taxi, roles: ROLE_TAXI }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/client, roles: ROLE_CLIENT }


