<?php

namespace Container69h5Jb4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTwilioServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TwilioService' shared autowired service.
     *
     * @return \App\Service\TwilioService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\TwilioService": argument "$twilioSid" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
