<?php

namespace Container8dTAiVo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZYF4_QuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zYF4.Qu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zYF4.Qu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['privates', '.errored.Ar9IwIa', NULL, 'Cannot determine controller argument for "App\\Controller\\Admin\\UserManagementController::deleteUsers()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'paginator' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
