<?php

namespace ContainerIyuxwfT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O4OSnBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o4OSn_B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o4OSn_B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'maintenance' => ['privates', '.errored..service_locator.o4OSn_B.App\\Entity\\Maintenance', NULL, 'Cannot autowire service ".service_locator.o4OSn_B": it needs an instance of "App\\Entity\\Maintenance" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'maintenance' => 'App\\Entity\\Maintenance',
        ]);
    }
}
