<?php

namespace ContainerIyuxwfT;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Odgi3jEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Odgi3jE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Odgi3jE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageUploader' => ['privates', 'App\\Service\\ImageUploadService', 'getImageUploadServiceService', true],
            'repository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService', true],
        ], [
            'em' => '?',
            'imageUploader' => 'App\\Service\\ImageUploadService',
            'repository' => 'App\\Repository\\VehicleRepository',
        ]);
    }
}
