<?php

namespace ContainerAuqEUYS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X_Po9DGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x.Po9DG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x.Po9DG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\UserManagementController::blockUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Admin\\UserManagementController::confirmDelete' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\Admin\\UserManagementController::deleteUsers' => ['privates', '.service_locator.lDw5jgg', 'get_ServiceLocator_LDw5jggService', true],
            'App\\Controller\\Admin\\UserManagementController::editUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Admin\\UserManagementController::manageUsers' => ['privates', '.service_locator.lDw5jgg', 'get_ServiceLocator_LDw5jggService', true],
            'App\\Controller\\Admin\\UserManagementController::performDelete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Admin\\UserManagementController::unblockUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Auth\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\Auth\\RegistrationController::register' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\Auth\\ResetPasswordController::request' => ['privates', '.service_locator.Xm4mt1I', 'get_ServiceLocator_Xm4mt1IService', true],
            'App\\Controller\\Auth\\ResetPasswordController::reset' => ['privates', '.service_locator.rET9i7U', 'get_ServiceLocator_RET9i7UService', true],
            'App\\Controller\\Auth\\ResetPasswordController::verifyCode' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ProfileController::delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProfileController::edit' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TestEmailController::testEmail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\UserManagementController:blockUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Admin\\UserManagementController:confirmDelete' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Controller\\Admin\\UserManagementController:deleteUsers' => ['privates', '.service_locator.lDw5jgg', 'get_ServiceLocator_LDw5jggService', true],
            'App\\Controller\\Admin\\UserManagementController:editUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Admin\\UserManagementController:manageUsers' => ['privates', '.service_locator.lDw5jgg', 'get_ServiceLocator_LDw5jggService', true],
            'App\\Controller\\Admin\\UserManagementController:performDelete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Admin\\UserManagementController:unblockUser' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\Auth\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\Auth\\RegistrationController:register' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\Auth\\ResetPasswordController:request' => ['privates', '.service_locator.Xm4mt1I', 'get_ServiceLocator_Xm4mt1IService', true],
            'App\\Controller\\Auth\\ResetPasswordController:reset' => ['privates', '.service_locator.rET9i7U', 'get_ServiceLocator_RET9i7UService', true],
            'App\\Controller\\Auth\\ResetPasswordController:verifyCode' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\ProfileController:delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ProfileController:edit' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\TestEmailController:testEmail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\UserManagementController::blockUser' => '?',
            'App\\Controller\\Admin\\UserManagementController::confirmDelete' => '?',
            'App\\Controller\\Admin\\UserManagementController::deleteUsers' => '?',
            'App\\Controller\\Admin\\UserManagementController::editUser' => '?',
            'App\\Controller\\Admin\\UserManagementController::manageUsers' => '?',
            'App\\Controller\\Admin\\UserManagementController::performDelete' => '?',
            'App\\Controller\\Admin\\UserManagementController::unblockUser' => '?',
            'App\\Controller\\Auth\\LoginController::index' => '?',
            'App\\Controller\\Auth\\RegistrationController::register' => '?',
            'App\\Controller\\Auth\\ResetPasswordController::request' => '?',
            'App\\Controller\\Auth\\ResetPasswordController::reset' => '?',
            'App\\Controller\\Auth\\ResetPasswordController::verifyCode' => '?',
            'App\\Controller\\ProfileController::delete' => '?',
            'App\\Controller\\ProfileController::edit' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TestEmailController::testEmail' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\UserManagementController:blockUser' => '?',
            'App\\Controller\\Admin\\UserManagementController:confirmDelete' => '?',
            'App\\Controller\\Admin\\UserManagementController:deleteUsers' => '?',
            'App\\Controller\\Admin\\UserManagementController:editUser' => '?',
            'App\\Controller\\Admin\\UserManagementController:manageUsers' => '?',
            'App\\Controller\\Admin\\UserManagementController:performDelete' => '?',
            'App\\Controller\\Admin\\UserManagementController:unblockUser' => '?',
            'App\\Controller\\Auth\\LoginController:index' => '?',
            'App\\Controller\\Auth\\RegistrationController:register' => '?',
            'App\\Controller\\Auth\\ResetPasswordController:request' => '?',
            'App\\Controller\\Auth\\ResetPasswordController:reset' => '?',
            'App\\Controller\\Auth\\ResetPasswordController:verifyCode' => '?',
            'App\\Controller\\ProfileController:delete' => '?',
            'App\\Controller\\ProfileController:edit' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TestEmailController:testEmail' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
