<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Taxi extends \App\Entity\Taxi implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'anneeFabrication' => [parent::class, 'anneeFabrication', null],
        "\0".parent::class."\0".'capacite' => [parent::class, 'capacite', null],
        "\0".parent::class."\0".'courses' => [parent::class, 'courses', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'immatriculation' => [parent::class, 'immatriculation', null],
        "\0".parent::class."\0".'licenceDateObtention' => [parent::class, 'licenceDateObtention', null],
        "\0".parent::class."\0".'licenceNumero' => [parent::class, 'licenceNumero', null],
        "\0".parent::class."\0".'marque' => [parent::class, 'marque', null],
        "\0".parent::class."\0".'modele' => [parent::class, 'modele', null],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null],
        "\0".parent::class."\0".'tarifBase' => [parent::class, 'tarifBase', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        "\0".parent::class."\0".'zoneDesserte' => [parent::class, 'zoneDesserte', null],
        'anneeFabrication' => [parent::class, 'anneeFabrication', null],
        'capacite' => [parent::class, 'capacite', null],
        'courses' => [parent::class, 'courses', null],
        'id' => [parent::class, 'id', null],
        'immatriculation' => [parent::class, 'immatriculation', null],
        'licenceDateObtention' => [parent::class, 'licenceDateObtention', null],
        'licenceNumero' => [parent::class, 'licenceNumero', null],
        'marque' => [parent::class, 'marque', null],
        'modele' => [parent::class, 'modele', null],
        'statut' => [parent::class, 'statut', null],
        'tarifBase' => [parent::class, 'tarifBase', null],
        'user' => [parent::class, 'user', null],
        'zoneDesserte' => [parent::class, 'zoneDesserte', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
