<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Trajet extends \App\Entity\Trajet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'arrivalTime' => [parent::class, 'arrivalTime', null],
        "\0".parent::class."\0".'availableSeats' => [parent::class, 'availableSeats', null],
        "\0".parent::class."\0".'departure' => [parent::class, 'departure', null],
        "\0".parent::class."\0".'departureTime' => [parent::class, 'departureTime', null],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null],
        "\0".parent::class."\0".'distance' => [parent::class, 'distance', null],
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'typeTransport' => [parent::class, 'typeTransport', null],
        "\0".parent::class."\0".'vehicleId' => [parent::class, 'vehicleId', null],
        'arrivalTime' => [parent::class, 'arrivalTime', null],
        'availableSeats' => [parent::class, 'availableSeats', null],
        'departure' => [parent::class, 'departure', null],
        'departureTime' => [parent::class, 'departureTime', null],
        'destination' => [parent::class, 'destination', null],
        'distance' => [parent::class, 'distance', null],
        'duration' => [parent::class, 'duration', null],
        'id' => [parent::class, 'id', null],
        'price' => [parent::class, 'price', null],
        'typeTransport' => [parent::class, 'typeTransport', null],
        'vehicleId' => [parent::class, 'vehicleId', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
