<?php

namespace ContainerLoJPV7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HRRA73wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hRRA73w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hRRA73w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'geocoder' => ['privates', 'App\\Service\\OpenCageGeocoder', 'getOpenCageGeocoderService', true],
        ], [
            'em' => '?',
            'geocoder' => 'App\\Service\\OpenCageGeocoder',
        ]);
    }
}
