<?php

namespace ContainerU03EE5D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GLNs2_ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gLNs2.Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gLNs2.Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'maintenanceRepository' => ['privates', 'App\\Repository\\MaintenanceRepository', 'getMaintenanceRepositoryService', true],
            'vehicleRepository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService', true],
        ], [
            'em' => '?',
            'maintenanceRepository' => 'App\\Repository\\MaintenanceRepository',
            'vehicleRepository' => 'App\\Repository\\VehicleRepository',
        ]);
    }
}
