# config/services.yaml

parameters:
    MAILER_FROM: '%env(MAILER_FROM)%'
    twilio_sid: '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_number: '%env(TWILIO_PHONE_NUMBER)%'
    recaptcha.site_key: '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha.secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    opencage.api_key: '%env(OPENCAGE_API_KEY)%'


twig:
    globals:
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\EventSubscriber\AuthenticationSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    # Makes all classes in src/ available as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicit service definitions (when autowiring isn't enough)
    App\Service\TwilioService:
        arguments:
            $twilioSid: '%twilio_sid%'
            $twilioToken: '%twilio_token%'
            $twilioNumber: '%twilio_number%'

    App\Service\RecaptchaValidator:
        arguments:
            $secretKey: '%recaptcha.secret_key%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    # Explicitly configure LoginController with the recaptcha site key
    App\Controller\Auth\LoginController:
        arguments:
            $recaptchaSiteKey: '%recaptcha.site_key%'

    # Controllers are registered as services
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Repositories are registered as services
    App\Repository\:
        resource: '../src/Repository/'
        tags: ['doctrine.repository_service']