# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    MAILER_FROM: '%env(MAILER_FROM)%'
    twilio_sid:   '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_number: '%env(TWILIO_PHONE_NUMBER)%'
    recaptcha.site_key:   '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha.secret_key: '%env(RECAPTCHA_SECRET_KEY)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\EventSubscriber\AuthenticationSubscriber:
        tags:
            - { name: kernel.event_subscriber }

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # explicit service definitions
    App\Service\TwilioService:
        arguments:
            $sid:    '%twilio_sid%'
            $token:  '%twilio_token%'
            $from:   '%twilio_number%'
            $logger: '@logger'

    App\Service\RecaptchaValidator:
        arguments:
            $secretKey: '%recaptcha.secret_key%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    App\Controller\Auth\LoginController:
        arguments:
            $recaptchaSiteKey: '%env(RECAPTCHA_SITE_KEY)%'
