# config/services.yaml

parameters:
    MAILER_FROM: '%env(MAILER_FROM)%'
    twilio_sid:   '%env(TWILIO_SID)%'
    twilio_token: '%env(TWILIO_AUTH_TOKEN)%'
    twilio_number: '%env(TWILIO_PHONE_NUMBER)%'
    recaptcha.site_key:   '%env(RECAPTCHA_SITE_KEY)%'
    recaptcha.secret_key: '%env(RECAPTCHA_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    opencage.api_key: '%env(OPENCAGE_API_KEY)%'
    app.user_image_upload_path: '%kernel.project_dir%/public/uploads/users/images'
    gemini_api_key: '%env(GEMINI_API_KEY)%'
    oauth.enabled: true
    oauth.google_enabled: true
    oauth.facebook_enabled: true
    gemini_model:   '%env(GEMINI_MODEL)%'
   # voicerss_key: '%env(VOICERSS_API_KEY)%'



twig:
    globals:
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\EventSubscriber\AuthenticationSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    # Makes all classes in src/ available as services
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicit service definitions (when autowiring isn't enough)
    App\Service\OpenCageGeocoder:
        arguments:
            $apiKey: '%env(OPENCAGE_API_KEY)%'
            
    App\Service\TwilioService:
        arguments:
            $sid:    '%twilio_sid%'
            $token:  '%twilio_token%'
            $from:   '%twilio_number%'
            $logger: '@logger'

    App\Service\RecaptchaValidator:
        arguments:
            $secretKey: '%recaptcha.secret_key%'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'

    # Explicitly configure LoginController with the recaptcha site key
    App\Controller\Auth\LoginController:
        arguments:
            $recaptchaSiteKey: '%recaptcha.site_key%'

    # Controllers are registered as services
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Repositories are registered as services
    App\Repository\:
        resource: '../src/Repository/'
        tags: ['doctrine.repository_service']

    App\Service\GeminiService:
        arguments:
            $client: '@http_client'  # Or the name of your HttpClient service
            $apiKey: '%env(GEMINI_API_KEY)%' # Assuming you store your API key in .env
            $doctrine: '@doctrine'

    App\Service\BadWordFilterService:
        arguments:
            $endpoint: 'https://www.purgomalum.com/service/plain'

   # App\Service\TextToSpeechService:
    #    arguments:
     #       $apiKey: '%voicerss_key%' 
      #      $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            
