<?php

namespace ContainerNdOTf8c;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CHwd4P5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cHwd4P5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cHwd4P5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'vehicle' => ['privates', '.errored..service_locator.cHwd4P5.App\\Entity\\Vehicle', NULL, 'Cannot autowire service ".service_locator.cHwd4P5": it needs an instance of "App\\Entity\\Vehicle" but this type has been excluded in "config/services.yaml".'],
            'vehicleRepository' => ['privates', 'App\\Repository\\VehicleRepository', 'getVehicleRepositoryService', true],
        ], [
            'vehicle' => 'App\\Entity\\Vehicle',
            'vehicleRepository' => 'App\\Repository\\VehicleRepository',
        ]);
    }
}
