# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection:
        enabled: true
    http_method_override: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax