parameters:
    # Your parameters (if any)
    MAILER_FROM: '%env(MAILER_FROM)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
twig:
    globals:
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    # Default configuration for services
    _defaults:
        autowire: true      # Automatically injects dependencies
        autoconfigure: true # Automatically registers services

    # Register the AuthenticationSubscriber service
    App\EventSubscriber\AuthenticationSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    # Service autodiscovery (excluding entities and tests)
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Controllers (explicitly register them as services)
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # Repositories (auto-registered by Doctrine)
    App\Repository\:
        resource: '../src/Repository/'
        tags: ['doctrine.repository_service']
    