<?php

namespace ContainerLx5M1aj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9Nk7qGcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9Nk7qGc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9Nk7qGc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'publisher' => ['privates', 'mercure.hub.default.publisher.traceable', 'getMercure_Hub_Default_Publisher_TraceableService', true],
        ], [
            'em' => '?',
            'publisher' => '?',
        ]);
    }
}
