<?php

namespace ContainerKiquVGc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ly3_N1TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ly3.N1T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ly3.N1T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\VehicleController::carousel' => ['privates', '.service_locator.cHwd4P5', 'get_ServiceLocator_CHwd4P5Service', true],
            'App\\Controller\\Admin\\VehicleController::create' => ['privates', '.service_locator.G.yWbMK', 'get_ServiceLocator_G_YWbMKService', true],
            'App\\Controller\\Admin\\VehicleController::delete' => ['privates', '.service_locator.L30Zz7t', 'get_ServiceLocator_L30Zz7tService', true],
            'App\\Controller\\Admin\\VehicleController::edit' => ['privates', '.service_locator.iEbu8P.', 'get_ServiceLocator_IEbu8P_Service', true],
            'App\\Controller\\Admin\\VehicleController::index' => ['privates', '.service_locator.d1U9zsJ', 'get_ServiceLocator_D1U9zsJService', true],
            'App\\Controller\\Admin\\VehicleController::show' => ['privates', '.service_locator.cHwd4P5', 'get_ServiceLocator_CHwd4P5Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\VehicleController:carousel' => ['privates', '.service_locator.cHwd4P5', 'get_ServiceLocator_CHwd4P5Service', true],
            'App\\Controller\\Admin\\VehicleController:create' => ['privates', '.service_locator.G.yWbMK', 'get_ServiceLocator_G_YWbMKService', true],
            'App\\Controller\\Admin\\VehicleController:delete' => ['privates', '.service_locator.L30Zz7t', 'get_ServiceLocator_L30Zz7tService', true],
            'App\\Controller\\Admin\\VehicleController:edit' => ['privates', '.service_locator.iEbu8P.', 'get_ServiceLocator_IEbu8P_Service', true],
            'App\\Controller\\Admin\\VehicleController:index' => ['privates', '.service_locator.d1U9zsJ', 'get_ServiceLocator_D1U9zsJService', true],
            'App\\Controller\\Admin\\VehicleController:show' => ['privates', '.service_locator.cHwd4P5', 'get_ServiceLocator_CHwd4P5Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\VehicleController::carousel' => '?',
            'App\\Controller\\Admin\\VehicleController::create' => '?',
            'App\\Controller\\Admin\\VehicleController::delete' => '?',
            'App\\Controller\\Admin\\VehicleController::edit' => '?',
            'App\\Controller\\Admin\\VehicleController::index' => '?',
            'App\\Controller\\Admin\\VehicleController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\VehicleController:carousel' => '?',
            'App\\Controller\\Admin\\VehicleController:create' => '?',
            'App\\Controller\\Admin\\VehicleController:delete' => '?',
            'App\\Controller\\Admin\\VehicleController:edit' => '?',
            'App\\Controller\\Admin\\VehicleController:index' => '?',
            'App\\Controller\\Admin\\VehicleController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
