<?php

namespace ContainerKiquVGc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IEbu8P_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iEbu8P.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iEbu8P.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'imageUploadService' => ['privates', 'App\\Service\\ImageUploadService', 'getImageUploadServiceService', true],
            'vehicle' => ['privates', '.errored..service_locator.iEbu8P..App\\Entity\\Vehicle', NULL, 'Cannot autowire service ".service_locator.iEbu8P.": it needs an instance of "App\\Entity\\Vehicle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'imageUploadService' => 'App\\Service\\ImageUploadService',
            'vehicle' => 'App\\Entity\\Vehicle',
        ]);
    }
}
