<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOOOE9Vw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOOOE9Vw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOOOE9Vw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOOOE9Vw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOOOE9Vw\App_KernelDevDebugContainer([
    'container.build_hash' => 'OOOE9Vw',
    'container.build_id' => 'a664bd24',
    'container.build_time' => 1745547209,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOOOE9Vw');
