<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCc74GzI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCc74GzI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCc74GzI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCc74GzI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCc74GzI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cc74GzI',
    'container.build_id' => 'fedaa252',
    'container.build_time' => 1746122918,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCc74GzI');
