<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMU6JtFZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMU6JtFZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMU6JtFZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMU6JtFZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMU6JtFZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'MU6JtFZ',
    'container.build_id' => 'f1e53517',
    'container.build_time' => 1743014634,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMU6JtFZ');
