<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAJAI9cY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAJAI9cY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAJAI9cY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAJAI9cY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAJAI9cY\App_KernelDevDebugContainer([
    'container.build_hash' => 'AJAI9cY',
    'container.build_id' => '371ac19e',
    'container.build_time' => 1744547655,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAJAI9cY');
