<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8mhr8N1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8mhr8N1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8mhr8N1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8mhr8N1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8mhr8N1\App_KernelDevDebugContainer([
    'container.build_hash' => '8mhr8N1',
    'container.build_id' => '12abeae1',
    'container.build_time' => 1744838877,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8mhr8N1');
