parameters:
    stripe_public_key: '%env(pk_test_51R8RSXFWe9kEcEpivcGYsMJln7VQy2nBRngo28AOxW4W5CH6lnofXcFxfdaBc4aZ9HAKiuhMUM561ayQe914UKUD001EZj3zC6)%'
    stripe_secret_key: '%env(sk_test_51R8RSXFWe9kEcEpioZfHiHz2ImTuKAiHA8zlJ1YWIUBEFYoMEqz7TSBluazC1sfIrvMfjBIChfUbMv7nyb6fMVMk00NQ8AyF5i)%'