<?php

namespace ContainerTRmI8Ut;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NmzH_DKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nmzH.DK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nmzH.DK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['privates', '.errored.uyQMC1i', NULL, 'Cannot determine controller argument for "App\\Controller\\Admin\\UserManagementController::manageUsers()": the $paginator argument is type-hinted with the non-existent class or interface: "Knp\\Component\\Pager\\PaginatorInterface".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'paginator' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
